// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/how-it-works/BentoGrid.tsx": () => import("../components/mockups/how-it-works/BentoGrid.tsx"),
  "./components/mockups/how-it-works/HorizontalTimeline.tsx": () => import("../components/mockups/how-it-works/HorizontalTimeline.tsx")
};
